### ISSUE TITLE
Server cannot be started when installation path of eclipse instance contains special character

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-eclipse#47]
```
java.net.URISyntaxException: Illegal character in path at index 23: file:/C:/Users/Aurelien Pupier/.p2/pool/plugins/com.github.camel-tooling.eclipse.client_1.0.0.201809120921/libs/camel-lsp-server-1.0.0-SNAPSHOT.jar
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:946)
	at com.github.cameltooling.eclipse.client.CamelLSPStreamConnectionProvider.computeCamelLanguageServerJarPath(CamelLSPStreamConnectionProvider.java:60)
	at com.github.cameltooling.eclipse.client.CamelLSPStreamConnectionProvider.computeCommands(CamelLSPStreamConnectionProvider.java:51)
	at com.github.cameltooling.eclipse.client.CamelLSPStreamConnectionProvider.<init>(CamelLSPStreamConnectionProvider.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:114)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:196)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrapperForConnection(LanguageServiceAccessor.java:340)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:299)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:444)
	at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:75)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by oznecniV97** [comment]
I have the same problem on path "C:/Program Files/Eclipse/Eclipse-2019-12/plugins/com.github.camel-tooling.eclipse.client_1.0.0.201909171309/libs/camel-lsp-server-1.1.0-SNAPSHOT.jar".

The problem is related to spaces in path, move eclipse installation under "C:/Eclipse/Eclipse-2019-12/" folder bypass this problem.
[eclipse.log](https://github.com/camel-tooling/camel-lsp-client-eclipse/files/4170972/eclipse.log)

**Comment by pamorimX** [comment]
> I have the same problem on path "C:/Program Files/Eclipse/Eclipse-2019-12/plugins/com.github.camel-tooling.eclipse.client_1.0.0.201909171309/libs/camel-lsp-server-1.1.0-SNAPSHOT.jar".
> 
> The problem is related to spaces in path, move eclipse installation under "C:/Eclipse/Eclipse-2019-12/" folder bypass this problem.
> [eclipse.log](https://github.com/camel-tooling/camel-lsp-client-eclipse/files/4170972/eclipse.log)

Thanks!

**Comment by apupier** [comment]
sounds to be caused by an old Eclipse issue which is marked as won't fix. A workaround  is provided in this comment https://bugs.eclipse.org/bugs/show_bug.cgi?id=145096#c23 to use org.eclipse.core.runtime.URIUtil.toURI(URL)
