### ISSUE TITLE
Fix issue reported by flaky test CamelLSPCompletionTest

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-eclipse#57]
15:34:32.115 INFO [WorkbenchTestable][WorkbenchShellHandler] Closing all shells...
15:34:32.115 DEBUG [WorkbenchTestable][AbstractWait] Waiting until active shell exists...
15:34:32.115 DEBUG [WorkbenchTestable][AbstractWait] Waiting until active shell exists finished successfully
15:34:32.119 ERROR [WorkbenchTestable][RequirementsRunner] Exception in test: testEndpointOptions no-configuration(com.github.cameltooling.lsp.ui.tests.CamelLSPCompletionTest)
org.eclipse.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: ContentAssistant shell is opened
	at org.eclipse.reddeer.common.wait.WaitUntil.throwWaitTimeOutException(WaitUntil.java:122)
	at org.eclipse.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:207)
	at org.eclipse.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:151)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:132)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:97)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:64)
	at org.eclipse.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:50)
	at org.eclipse.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:38)
	at org.eclipse.reddeer.workbench.impl.editor.AbstractEditor.getContentAssistantShell(AbstractEditor.java:231)
	at org.eclipse.reddeer.workbench.impl.editor.AbstractEditor.openContentAssistant(AbstractEditor.java:207)
	at org.eclipse.reddeer.workbench.impl.editor.AbstractEditor.openContentAssistant(AbstractEditor.java:177)
	at com.github.cameltooling.lsp.ui.tests.CamelLSPCompletionTest.tryEndpointOptionsCompletion(CamelLSPCompletionTest.java:197)
	at com.github.cameltooling.lsp.ui.tests.CamelLSPCompletionTest.testEndpointOptions(CamelLSPCompletionTest.java:118)

**Comment by apupier** [comment]
i'm noticing this test failing more often recently.

providing stack in case it has changed a bit.

@djelinek @tsedmik @jkopriva Can you plan to have a look one of those weeks please?

```
testEndpointOptions no-configuration(com.github.cameltooling.lsp.ui.tests.CamelLSPCompletionTest)  Time elapsed: 14.342 s  <<< ERROR!
4525org.eclipse.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: ContentAssistant shell is opened
4526	at com.github.cameltooling.lsp.ui.tests.CamelLSPCompletionTest.tryEndpointOptionsCompletion(CamelLSPCompletionTest.java:193)
4527	at com.github.cameltooling.lsp.ui.tests.CamelLSPCompletionTest.testEndpointOptions(CamelLSPCompletionTest.java:118)
```
